# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fincnic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  # Pods for Fincnic

  target 'FincnicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FincnicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
