# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hanyang University' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hanyang University
  pod 'Firebase/Core'
  target 'Hanyang UniversityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hanyang UniversityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
